name: v3xt Build

on:
  push:
    paths:
    - "src/main/**"
    - "v3xt/src/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x ./v3xt/gradlew
    - name: Build with Gradle
      working-directory: ./v3xt
      run: ./gradlew build -x test
